// Generated by scripts/prep-footage.sh: the recorded takes and their frame counts.
const FOOTAGE = {
 "r1-parcel": {
  "frames": 489,
  "w": 1920,
  "h": 1080
 },
 "r2-georef": {
  "frames": 279,
  "w": 1920,
  "h": 1080
 },
 "r3-terrain": {
  "frames": 153,
  "w": 1920,
  "h": 1080
 },
 "r4-hydro": {
  "frames": 237,
  "w": 1920,
  "h": 1080
 },
 "r5-viewshed": {
  "frames": 178,
  "w": 1920,
  "h": 1080
 },
 "r6-export": {
  "frames": 494,
  "w": 1920,
  "h": 1080
 },
 "r78-field": {
  "frames": 719,
  "w": 1170,
  "h": 2532
 },
 "r9-poker": {
  "frames": 447,
  "w": 1170,
  "h": 2532
 }
};
