#!/usr/bin/env bash
# Extracts every take in footage/*.mp4 to footage/frames/<take>/f00001.jpg... and writes footage/frames/index.js
# (FOOTAGE: frames, width, height per take) for src/footage.js. Re-run after re-recording a take.
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p footage/frames
for mp4 in footage/*.mp4; do
  name=$(basename "$mp4" .mp4); dir="footage/frames/$name"
  if [ -d "$dir" ] && [ "$dir" -nt "$mp4" ]; then continue; fi
  rm -rf "$dir"; mkdir -p "$dir"
  ffmpeg -v error -i "$mp4" -q:v 2 "$dir/f%05d.jpg"
  echo "$name: $(ls "$dir" | wc -l) frames"
done
python3 -I - <<'PY'
import os, json, subprocess
idx = {}
for name in sorted(os.listdir('footage/frames')):
    d = f'footage/frames/{name}'
    if not os.path.isdir(d): continue
    n = len([f for f in os.listdir(d) if f.endswith('.jpg')])
    w, h = subprocess.run(['ffprobe','-v','error','-select_streams','v:0','-show_entries','stream=width,height','-of','csv=p=0',f'footage/{name}.mp4'],capture_output=True,text=True).stdout.strip().split(',')
    idx[name] = {'frames': n, 'w': int(w), 'h': int(h)}
open('footage/frames/index.js','w').write('// Generated by scripts/prep-footage.sh: the recorded takes and their frame counts.\nconst FOOTAGE = ' + json.dumps(idx, indent=1) + ';\n')
print(json.dumps(idx))
PY
